baseURL = 'https://example.org/'
languageCode = 'ja-jp'
title = 'oTree の登り方'
theme = 'hugo-theme-relearn'

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
    BookSection = "*"
    customCSS = ["css/custom.css"]

    # Relearn theme parameters
    showVisitedLinks = true
    disableBreadcrumb = false
    disableNextPrev = false
    themeVariant = "relearn-light"

    # Search
    search.disable = false
    disableSearchHiddenPages = true

    # MathJax をグローバルで有効化
    mathJax = true

    # インラインコードのコピーボタンを無効化
    disableInlineCopyToClipBoard = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Markdown 内の HTML を許可
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"
