baseURL = 'https://example.org/'
languageCode = 'ja-jp'
title = 'oTree の登り方'
theme = 'hugo-theme-relearn'

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
    BookSection = "*"
    customCSS = ["css/custom.css"]
